package com.marukhin.tuturuapp.core.db.models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.marukhin.tuturuapp.core.db.models.City;
import com.marukhin.tuturuapp.core.db.models.Destination;
import com.marukhin.tuturuapp.core.db.models.Station;

import com.marukhin.tuturuapp.core.db.models.CityDao;
import com.marukhin.tuturuapp.core.db.models.DestinationDao;
import com.marukhin.tuturuapp.core.db.models.StationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig destinationDaoConfig;
    private final DaoConfig stationDaoConfig;

    private final CityDao cityDao;
    private final DestinationDao destinationDao;
    private final StationDao stationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        destinationDaoConfig = daoConfigMap.get(DestinationDao.class).clone();
        destinationDaoConfig.initIdentityScope(type);

        stationDaoConfig = daoConfigMap.get(StationDao.class).clone();
        stationDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        destinationDao = new DestinationDao(destinationDaoConfig, this);
        stationDao = new StationDao(stationDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(Destination.class, destinationDao);
        registerDao(Station.class, stationDao);
    }
    
    public void clear() {
        cityDaoConfig.clearIdentityScope();
        destinationDaoConfig.clearIdentityScope();
        stationDaoConfig.clearIdentityScope();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public DestinationDao getDestinationDao() {
        return destinationDao;
    }

    public StationDao getStationDao() {
        return stationDao;
    }

}
